Check VERSION before running

diff --git a/.github/workflows/build-and-publish.yml b/.github/workflows/build-and-publish.yml
--- a/.github/workflows/build-and-publish.yml
+++ b/.github/workflows/build-and-publish.yml
@@ -14,6 +14,15 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+    - name: Check if VERSION is set
+      run: |
+        if [ -z "$VERSION" ]; then
+          echo "Error: VERSION is not set."
+          exit 1
+        else
+          echo "VERSION is set to $VERSION"
+        fi
+    
     # Checkout the repository
     - name: Checkout code
       uses: actions/checkout@v3
